spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${host}:${port}/${database}?useLegacyDatetimeCode=false&serverTimezone=${serverTimezone}
    username: ${username}
    password: ${password}

  jpa:
    hibernate:
      ddl-auto: update
